import type {
  Destination,
  Challenge,
  Business,
  User,
  Report,
  AIInsight,
  SocialPost,
  Creator,
  Campaign,
  Badge,
  Attraction,
} from '@/types'

// ─── Users ──────────────────────────────────────────────────────────────────
export const currentUser: User = {
  id: 'user-1',
  displayName: 'Priya Sharma',
  username: '@priyatravels',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&auto=format',
  bio: 'Sustainable travel enthusiast. Exploring India responsibly.',
  role: 'traveler',
  impactPoints: 420,
  challengesCompleted: 8,
  destinationsVisited: 5,
  badgesEarned: 6,
  co2Avoided: 12.5,
}

export const demoUsers: User[] = [
  currentUser,
  {
    id: 'user-2',
    displayName: 'Arjun Mehta',
    username: '@arjun_eco',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&auto=format',
    bio: 'Eco-warrior and trail explorer',
    role: 'traveler',
    impactPoints: 380,
    challengesCompleted: 7,
    destinationsVisited: 4,
    badgesEarned: 5,
    co2Avoided: 9.2,
  },
  {
    id: 'user-3',
    displayName: 'Sneha Patel',
    username: '@snehawanders',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&auto=format',
    bio: 'Travel creator & responsible tourism advocate',
    role: 'creator',
    impactPoints: 650,
    challengesCompleted: 15,
    destinationsVisited: 8,
    badgesEarned: 10,
    co2Avoided: 22.1,
  },
]

// ─── Destinations ───────────────────────────────────────────────────────────
export const destinations: Destination[] = [
  {
    id: 'matheran',
    name: 'Matheran',
    region: 'Maharashtra',
    country: 'India',
    description:
      'Asia\'s only automobile-free hill station in the Sahyadri Western Ghats, renowned for red laterite trails, 1907 heritage toy train, and biodiverse evergreen forest cover.',
    heroImageUrl: 'https://www.clubmahindra.com/blog/images/Matheran-resized.jpg',
    sustainabilityScore: 82,
    visitorPressure: 'High',
    wastePressure: 'Medium',
    waterPressure: 'Low',
    environmentalSensitivity: 'High',
    crowdLevel: 'High',
    accessibilitySummary: 'Walking-heavy eco sanctuary. Toy train provides scenic access. Main market is flat with accessible hand-pulled rickshaws.',
    factors: [
      { factor: 'Environmental Health', score: 88, explanation: 'Vehicle-free zone, zero vehicular emissions, dense Sahyadri forest', icon: '🌿' },
      { factor: 'Waste Management', score: 72, explanation: 'Community trash-back initiative active at entry toll gate', icon: '♻️' },
      { factor: 'Water Sustainability', score: 85, explanation: 'Charlotte Lake reservoir conservation active', icon: '💧' },
      { factor: 'Mobility', score: 65, explanation: 'Vehicle-free zone is eco-friendly but requires walking/horse trails', icon: '🚶' },
      { factor: 'Visitor Pressure', score: 58, explanation: 'Weekend crowds create pressure on Louisa & Panorama viewpoints', icon: '👥' },
      { factor: 'Local Community', score: 80, explanation: '100% locally owned horse guides, porters, and heritage chikki artisans', icon: '🏘️' },
      { factor: 'Accessibility', score: 55, explanation: 'Unpaved red earth trails require sturdy walking assistance', icon: '♿' },
      { factor: 'Sustainable Hospitality', score: 78, explanation: 'Heritage colonial bungalows converted to solar-powered eco-stays', icon: '🏨' },
    ],
    accessibility: {
      wheelchairAccessible: false,
      stepFreeRoutes: false,
      accessibleToilets: false,
      elevator: false,
      accessibleParking: true,
      lowWalkingRequirement: false,
      trailDifficulty: 'Moderate',
      notes: 'Matheran is a pedestrian eco-sanctuary. Toy train connects Neral to Aman Lodge. Main market area is relatively navigable.',
    },
    tags: ['hill-station', 'nature', 'eco-friendly', 'walking', 'heritage-railway'],
    image: 'https://www.clubmahindra.com/blog/images/Matheran-resized.jpg',
  },
  {
    id: 'goa',
    name: 'Goa',
    region: 'Goa',
    country: 'India',
    description:
      'India\'s coastal jewel combining serene South Goa crescent beaches, Latin Quarter Fontainhas heritage, river backwaters, and organic spice biodiversity farms.',
    heroImageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&h=700&fit=crop&auto=format',
    sustainabilityScore: 71,
    visitorPressure: 'Very High',
    wastePressure: 'High',
    waterPressure: 'Medium',
    environmentalSensitivity: 'High',
    crowdLevel: 'Very High',
    accessibilitySummary: 'Beach accessibility varies. South Goa (Palolem, Agonda) is more relaxed with beach ramps; North Goa is more commercial.',
    factors: [
      { factor: 'Environmental Health', score: 65, explanation: 'Coastal mangrove protection programs active in Mandovi basin', icon: '🌿' },
      { factor: 'Waste Management', score: 55, explanation: 'High seasonal waste generation; beach cleanup drives active', icon: '♻️' },
      { factor: 'Water Sustainability', score: 68, explanation: 'Seasonal water rationing in coastal resort belts', icon: '💧' },
      { factor: 'Mobility', score: 75, explanation: 'Good EV scooter rental network and ferry crossings across islands', icon: '🚶' },
      { factor: 'Visitor Pressure', score: 45, explanation: 'Heavy peak winter crowding in Calangute; peaceful in South Goa', icon: '👥' },
      { factor: 'Local Community', score: 70, explanation: 'Kunbi weaving & authentic Goan homestays supported', icon: '🏘️' },
      { factor: 'Accessibility', score: 72, explanation: 'Better road infrastructure and beach matting installations', icon: '♿' },
      { factor: 'Sustainable Hospitality', score: 76, explanation: 'Green certified beach huts and organic permaculture retreats', icon: '🏨' },
    ],
    accessibility: {
      wheelchairAccessible: true,
      stepFreeRoutes: true,
      accessibleToilets: true,
      elevator: false,
      accessibleParking: true,
      lowWalkingRequirement: true,
      trailDifficulty: 'Easy',
      notes: 'South Goa beaches tend to be more accessible with beach-accessible matting and ramps. Divar island ferry has wheelchair roll-on.',
    },
    tags: ['beach', 'heritage', 'coastal', 'spice-farms', 'islands'],
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'manali',
    name: 'Manali',
    region: 'Himachal Pradesh',
    country: 'India',
    description:
      'A majestic mountain sanctuary in the Kullu Valley, featuring snow-capped Himalayan peaks, sacred cedar deodar forests, ancient wooden pagodas, and apple orchard treks.',
    heroImageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&h=700&fit=crop&auto=format',
    sustainabilityScore: 68,
    visitorPressure: 'High',
    wastePressure: 'High',
    waterPressure: 'Medium',
    environmentalSensitivity: 'High',
    crowdLevel: 'High',
    accessibilitySummary: 'Challenging high-altitude terrain. Valley floor and Old Manali town are walkable; trekking routes require moderate fitness.',
    factors: [
      { factor: 'Environmental Health', score: 72, explanation: 'Pristine Himalayan ecosystems under glacier protection mandates', icon: '🌿' },
      { factor: 'Waste Management', score: 52, explanation: 'Strict ban on plastic bottles in Rohtang ecological corridor', icon: '♻️' },
      { factor: 'Water Sustainability', score: 70, explanation: 'Abundant glacial streams with micro-hydro catchment', icon: '💧' },
      { factor: 'Mobility', score: 50, explanation: 'Mountain pass terrain; shared electric buses on Solang corridor', icon: '🚶' },
      { factor: 'Visitor Pressure', score: 48, explanation: 'High peak holiday traffic; dispersal programs active to Naggar & Sethan', icon: '👥' },
      { factor: 'Local Community', score: 75, explanation: 'Traditional Kullu shawls, apple farming, and indigenous Himachali crafts', icon: '🏘️' },
      { factor: 'Accessibility', score: 42, explanation: 'Steep inclines and stone stairways at historic temple sites', icon: '♿' },
      { factor: 'Sustainable Hospitality', score: 68, explanation: 'Pioneer mud-and-wood Kath-Kuni eco-homestays', icon: '🏨' },
    ],
    accessibility: {
      wheelchairAccessible: false,
      stepFreeRoutes: false,
      accessibleToilets: false,
      elevator: false,
      accessibleParking: true,
      lowWalkingRequirement: false,
      trailDifficulty: 'Difficult',
      notes: 'Mountain terrain (2,050m elevation). Hadimba temple has flat wooden perimeter paths. Vashisht village has steep paved stairs.',
    },
    tags: ['mountains', 'snow-peaks', 'adventure', 'ancient-temples', 'himachal'],
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'munnar',
    name: 'Munnar',
    region: 'Kerala',
    country: 'India',
    description:
      'Sprawling emerald green tea estates in the Western Ghats, misty mountain valleys, Eravikulam National Park, and sustainable spice trails in God\'s Own Country.',
    heroImageUrl: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200&h=700&fit=crop&auto=format',
    sustainabilityScore: 86,
    visitorPressure: 'Medium',
    wastePressure: 'Low',
    waterPressure: 'Low',
    environmentalSensitivity: 'High',
    crowdLevel: 'Medium',
    accessibilitySummary: 'Tea garden view points accessible via scenic roads. Eravikulam park provides safari minibuses with ramp access.',
    factors: [
      { factor: 'Environmental Health', score: 92, explanation: 'World heritage biodiversity hotspot; Nilgiri Tahr habitat protection', icon: '🌿' },
      { factor: 'Waste Management', score: 84, explanation: 'Haritha Karma Sena zero-waste community processing active', icon: '♻️' },
      { factor: 'Water Sustainability', score: 89, explanation: 'Perennial mountain springs and sustainable tea estate rainwater harvesting', icon: '💧' },
      { factor: 'Mobility', score: 72, explanation: 'Electric safari shuttles and well-graded plantation walk routes', icon: '🚶' },
      { factor: 'Visitor Pressure', score: 68, explanation: 'Time-slotted visitor caps for national park viewpoints', icon: '👥' },
      { factor: 'Local Community', score: 88, explanation: 'Cooperative tea worker estates and indigenous spice cultivators', icon: '🏘️' },
      { factor: 'Accessibility', score: 62, explanation: 'Safari buses equipped with boarding assistance; gentle tea trail paths', icon: '♿' },
      { factor: 'Sustainable Hospitality', score: 85, explanation: 'Extensive certified organic plantation resorts and treehouse stays', icon: '🏨' },
    ],
    accessibility: {
      wheelchairAccessible: true,
      stepFreeRoutes: true,
      accessibleToilets: true,
      elevator: false,
      accessibleParking: true,
      lowWalkingRequirement: true,
      trailDifficulty: 'Easy',
      notes: 'Eravikulam National Park features paved accessible trails at Rajamalai base. Tea museum has complete step-free access.',
    },
    tags: ['tea-gardens', 'western-ghats', 'wildlife', 'kerala', 'eco-resorts'],
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop&auto=format',
  },
]

// ─── Attractions ────────────────────────────────────────────────────────────
export const attractions: Attraction[] = [
  // Matheran
  {
    id: 'toy-train',
    destinationId: 'matheran',
    name: 'Matheran Heritage Toy Train',
    description: 'A 1907 UNESCO tentative narrow-gauge mountain railway winding through pristine Sahyadri forest slopes.',
    crowdLevel: 'Medium',
    sustainabilityScore: 88,
    accessibilityScore: 65,
    estimatedCost: 150,
    travelTime: '30 min ride',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'louisa-point',
    destinationId: 'matheran',
    name: 'Louisa Point & Prabal Fort Vista',
    description: 'Dramatic mountain cliff edge offering expansive views of ancient Prabal Fort and verdant canyon valleys.',
    crowdLevel: 'Medium',
    sustainabilityScore: 80,
    accessibilityScore: 50,
    estimatedCost: 0,
    travelTime: '20 min walk',
    image: 'https://www.clubmahindra.com/blog/images/Matheran-resized.jpg',
  },
  {
    id: 'forest-trail',
    destinationId: 'matheran',
    name: 'Charlotte Lake & Forest Trail',
    description: 'A peaceful vehicle-free forest canopy trail encircling Charlotte Lake, home to rare Malabar whistling thrushes.',
    crowdLevel: 'Low',
    sustainabilityScore: 92,
    accessibilityScore: 45,
    estimatedCost: 0,
    travelTime: '30 min walk',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'echo-point',
    destinationId: 'matheran',
    name: 'Echo Point & Sahyadri Ridge',
    description: 'A popular high cliff point producing natural acoustic echoes across deep Sahyadri gorges.',
    crowdLevel: 'High',
    sustainabilityScore: 75,
    accessibilityScore: 40,
    estimatedCost: 0,
    travelTime: '15 min walk',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&h=600&fit=crop&auto=format',
    alternativeId: 'forest-trail',
  },
  {
    id: 'panorama-point',
    destinationId: 'matheran',
    name: 'Panorama Point 360° Lookout',
    description: 'The highest summit in Matheran offering complete 360-degree panoramic views of sunrise over Ulhas valley.',
    crowdLevel: 'High',
    sustainabilityScore: 70,
    accessibilityScore: 35,
    estimatedCost: 0,
    travelTime: '25 min walk',
    image: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800&h=600&fit=crop&auto=format',
  },
  // Goa
  {
    id: 'palolem-beach',
    destinationId: 'goa',
    name: 'Palolem Beach, South Goa',
    description: 'A world-famous crescent-shaped golden beach backed by towering coconut groves and eco-certified wooden shacks.',
    crowdLevel: 'Medium',
    sustainabilityScore: 78,
    accessibilityScore: 70,
    estimatedCost: 0,
    travelTime: '10 min drive',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'cabo-de-rama',
    destinationId: 'goa',
    name: 'Cabo de Rama Fort & Coastal Cliffs',
    description: 'Historic coastal fortress overlooking dramatic ocean cliffs and secluded emerald waters in Canacona.',
    crowdLevel: 'Low',
    sustainabilityScore: 86,
    accessibilityScore: 50,
    estimatedCost: 0,
    travelTime: '30 min drive',
    image: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'spice-plantation',
    destinationId: 'goa',
    name: 'Sahakari Organic Spice Farm, Ponda',
    description: 'An authentic multi-crop organic spice plantation with farmer-guided walks through cardamom, vanilla, and pepper vines.',
    crowdLevel: 'Low',
    sustainabilityScore: 92,
    accessibilityScore: 60,
    estimatedCost: 400,
    travelTime: '45 min drive',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'divar-island',
    destinationId: 'goa',
    name: 'Divar Island Heritage Trail',
    description: 'A serene Mandovi river island with baroque Portuguese churches, traditional Indo-Portuguese villas, and scenic cycling roads.',
    crowdLevel: 'Low',
    sustainabilityScore: 90,
    accessibilityScore: 55,
    estimatedCost: 20,
    travelTime: '30 min ferry',
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop&auto=format',
  },
  // Manali / Himachal Pradesh
  {
    id: 'hadimba-temple',
    destinationId: 'manali',
    name: 'Hadimba Wooden Cave Temple',
    description: 'A 16th-century four-tier wooden pagoda temple nestled deep inside an ancient deodar cedar forest in Old Manali.',
    crowdLevel: 'High',
    sustainabilityScore: 72,
    accessibilityScore: 50,
    estimatedCost: 0,
    travelTime: '10 min drive',
    image: 'https://images.unsplash.com/photo-1713981275025-03497dcb375c?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'solang-valley',
    destinationId: 'manali',
    name: 'Solang Valley Alpine Meadow',
    description: 'Spectacular snow-peaked Himalayan valley offering eco-friendly snow walks, horse trails, and zero-emission dispersal zones.',
    crowdLevel: 'High',
    sustainabilityScore: 68,
    accessibilityScore: 55,
    estimatedCost: 0,
    travelTime: '30 min drive',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop&auto=format',
  },
  {
    id: 'jogini-waterfall',
    destinationId: 'manali',
    name: 'Jogini Waterfall Pine Forest Trek',
    description: 'A pristine nature trail through apple orchards and whispering pine forests leading to a cascading glacial waterfall.',
    crowdLevel: 'Medium',
    sustainabilityScore: 88,
    accessibilityScore: 35,
    estimatedCost: 0,
    travelTime: '2.5 hr trek',
    image: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=800&h=600&fit=crop&auto=format',
  },
  // Munnar / Kerala
  {
    id: 'kolukkumalai-tea',
    destinationId: 'munnar',
    name: 'Kolukkumalai Organic Tea Plantation',
    description: 'The highest tea plantation in the world, producing orthodox organic tea amid mist-shrouded green peaks.',
    crowdLevel: 'Low',
    sustainabilityScore: 94,
    accessibilityScore: 60,
    estimatedCost: 200,
    travelTime: '45 min drive',
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=600&fit=crop&auto=format',
  },
]

// ─── Challenges ─────────────────────────────────────────────────────────────
export const challenges: Challenge[] = [
  // Matheran
  {
    id: 'ch-matheran-1',
    destinationId: 'matheran',
    title: 'Waste-Free Trail',
    description: 'Complete a trail walk while collecting and properly disposing of any litter you find along the way.',
    category: 'environment',
    difficulty: 'Easy',
    points: 25,
    estimatedMinutes: 60,
    instructions: [
      'Choose any trail in Matheran',
      'Carry a small bag for litter collection',
      'Collect at least 3 pieces of litter',
      'Dispose of collected waste at designated bins',
      'Upload a photo of your collected waste with the trail in the background',
    ],
    evidenceRequired: true,
    whyItMatters: 'Matheran generates increasing waste during peak tourist season. Every piece of litter collected helps maintain the natural beauty of this hill station.',
    icon: '♻️',
  },
  {
    id: 'ch-matheran-2',
    destinationId: 'matheran',
    title: 'Refill Champion',
    description: 'Use refillable water bottles for an entire day and avoid single-use plastic water bottles.',
    category: 'sustainability',
    difficulty: 'Easy',
    points: 20,
    estimatedMinutes: 480,
    instructions: [
      'Carry a refillable water bottle',
      'Use refill stations at hotels, restaurants, or public taps',
      'Do not purchase any plastic water bottles',
      'Photograph your refillable bottle at 2 different refill points',
    ],
    evidenceRequired: true,
    whyItMatters: 'Single-use plastic bottles are one of the biggest waste contributors in hill stations. Refilling reduces plastic waste significantly.',
    icon: '💧',
  },
  {
    id: 'ch-matheran-3',
    destinationId: 'matheran',
    title: 'Local Supporter',
    description: 'Purchase one product from a verified local artisan or community enterprise.',
    category: 'community',
    difficulty: 'Easy',
    points: 30,
    estimatedMinutes: 45,
    instructions: [
      'Visit the Matheran local market',
      'Purchase a product directly from a local artisan',
      'Ensure the product is locally made (not mass-produced)',
      'Upload a photo with the artisan or their stall',
    ],
    evidenceRequired: true,
    whyItMatters: 'Supporting local artisans keeps traditional crafts alive and ensures tourism revenue benefits the local community directly.',
    icon: '🏘️',
  },
  {
    id: 'ch-matheran-4',
    destinationId: 'matheran',
    title: 'Trail Guardian',
    description: 'Stay on designated trails and encourage others to do the same during your visit.',
    category: 'conservation',
    difficulty: 'Medium',
    points: 35,
    estimatedMinutes: 120,
    instructions: [
      'Choose a trail to explore',
      'Stay on marked paths throughout the walk',
      'Take a photo at the trail marker/sign',
      'Upload a selfie on the designated path',
    ],
    evidenceRequired: true,
    whyItMatters: 'Off-trail walking damages fragile ecosystems and accelerates soil erosion in sensitive hill station environments.',
    icon: '🌿',
  },
  {
    id: 'ch-matheran-5',
    destinationId: 'matheran',
    title: 'Zero Carbon Commute',
    description: 'Use walking or the toy train instead of any motorized transport for a full day.',
    category: 'transport',
    difficulty: 'Medium',
    points: 40,
    estimatedMinutes: 480,
    instructions: [
      'Plan your day using only walking or toy train',
      'Do not use any private vehicles or taxis',
      'Upload a photo from your walking route or the toy train',
    ],
    evidenceRequired: true,
    whyItMatters: 'Matheran\'s vehicle-free status is its greatest asset. Walking reduces pollution and preserves the hill station\'s unique character.',
    icon: '🚶',
  },
  // Goa
  {
    id: 'ch-goa-1',
    destinationId: 'goa',
    title: 'Beach Cleanup Warrior',
    description: 'Participate in a beach cleanup by collecting and disposing of waste found on the shore.',
    category: 'environment',
    difficulty: 'Easy',
    points: 30,
    estimatedMinutes: 60,
    instructions: [
      'Visit any beach in Goa',
      'Spend 30 minutes collecting litter',
      'Dispose of waste at designated bins',
      'Upload a photo of collected waste with the beach',
    ],
    evidenceRequired: true,
    whyItMatters: 'Goa\'s beaches accumulate significant waste from tourists and ocean currents. Beach cleanups directly protect marine life.',
    icon: '🏖️',
  },
  {
    id: 'ch-goa-2',
    destinationId: 'goa',
    title: 'Local Food Explorer',
    description: 'Eat at a locally-owned restaurant that serves traditional Goan cuisine instead of chain restaurants.',
    category: 'community',
    difficulty: 'Easy',
    points: 20,
    estimatedMinutes: 60,
    instructions: [
      'Find a locally-owned restaurant',
      'Order traditional Goan food',
      'Upload a photo of your meal',
    ],
    evidenceRequired: true,
    whyItMatters: 'Local restaurants preserve Goan culinary traditions and keep tourism spending within the community.',
    icon: '🍛',
  },
  // Manali
  {
    id: 'ch-manali-1',
    destinationId: 'manali',
    title: 'Mountain Trail Respecter',
    description: 'Trek only on marked trails and document responsible mountain behavior.',
    category: 'conservation',
    difficulty: 'Medium',
    points: 35,
    estimatedMinutes: 180,
    instructions: [
      'Choose a marked trek',
      'Stay on the designated path',
      'Carry back all waste',
      'Upload a photo at the trail marker',
    ],
    evidenceRequired: true,
    whyItMatters: 'Mountain ecosystems are extremely fragile. Off-trail trekking causes erosion and damages alpine vegetation.',
    icon: '🏔️',
  },
]

// ─── Businesses ─────────────────────────────────────────────────────────────
export const businesses: Business[] = [
  {
    id: 'biz-1',
    destinationId: 'matheran',
    name: 'Green Valley Heritage Cottage',
    type: 'homestay',
    description: 'A traditional 1920s Sahyadri heritage cottage surrounded by organic gardens, offering local Maharashtrian hospitality and solar power.',
    imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop&auto=format',
    sustainabilityScore: 88,
    accessibilitySummary: 'Step-free entrance, ground floor veranda accessible.',
    sustainabilityPractices: ['Solar energy', 'Water conservation', 'Waste segregation', 'Local employment', 'Organic garden'],
    accessibilityFeatures: [
      { feature: 'Step-free entrance', available: true },
      { feature: 'Accessible parking', available: true },
      { feature: 'Accessible toilet', available: true },
      { feature: 'Elevator', available: false },
      { feature: 'Accessible rooms', available: false },
    ],
    priceRange: '₹1,800–2,800/night',
    rating: 4.8,
    reviews: 142,
  },
  {
    id: 'biz-2',
    destinationId: 'matheran',
    name: 'Matheran Forest Organic Café',
    type: 'restaurant',
    description: 'A cozy forest café serving farm-to-table organic meals, herbal infusions, and fresh local chikki with zero single-use plastic.',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop&auto=format',
    sustainabilityScore: 92,
    accessibilitySummary: 'Ground floor open terrace accessible.',
    sustainabilityPractices: ['Composting', 'Zero plastic policy', 'Local sourcing', 'Rainwater harvesting'],
    accessibilityFeatures: [
      { feature: 'Step-free entrance', available: true },
      { feature: 'Accessible parking', available: true },
      { feature: 'Accessible toilet', available: false },
      { feature: 'Elevator', available: false },
      { feature: 'Accessible rooms', available: false },
    ],
    priceRange: '₹350–700/meal',
    rating: 4.7,
    reviews: 110,
  },
  {
    id: 'biz-3',
    destinationId: 'goa',
    name: 'Palolem Eco Lagoon Resort',
    type: 'resort',
    description: 'A certified green beach eco-retreat in South Goa built from sustainably harvested bamboo and thatch, powered 100% by solar micro-grids.',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop&auto=format',
    sustainabilityScore: 94,
    accessibilitySummary: 'Complete step-free beachfront boardwalks with beach wheelchair support.',
    sustainabilityPractices: ['100% Solar power', 'Turtle nesting zone protection', 'Organic farm kitchen', 'Greywater bio-filter', 'EV scooter charging'],
    accessibilityFeatures: [
      { feature: 'Step-free entrance', available: true },
      { feature: 'Accessible parking', available: true },
      { feature: 'Accessible toilet', available: true },
      { feature: 'Elevator', available: false },
      { feature: 'Accessible rooms', available: true },
    ],
    priceRange: '₹4,500–8,500/night',
    rating: 4.9,
    reviews: 268,
  },
  {
    id: 'biz-4',
    destinationId: 'goa',
    name: 'Sahakari Farm Spice Walks',
    type: 'experience',
    description: 'Guided regenerative agriculture tours through centuries-old spice forests with local botanical guides and traditional Goan lunch.',
    imageUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&h=600&fit=crop&auto=format',
    sustainabilityScore: 95,
    accessibilitySummary: 'Main spice trail is level and stroller/wheelchair friendly.',
    sustainabilityPractices: ['Organic polyculture', 'Zero synthetic pesticide', 'Local indigenous employment', 'Seed bank conservation'],
    accessibilityFeatures: [
      { feature: 'Step-free entrance', available: true },
      { feature: 'Accessible parking', available: true },
      { feature: 'Accessible toilet', available: true },
      { feature: 'Elevator', available: false },
      { feature: 'Accessible rooms', available: false },
    ],
    priceRange: '₹500–900/person',
    rating: 4.9,
    reviews: 195,
  },
  {
    id: 'biz-5',
    destinationId: 'manali',
    name: 'Kath-Kuni Himalayan Eco Sanctuary',
    type: 'lodge',
    description: 'An authentic mountain sanctuary built with traditional Himachali interlocking deodar wood and stone (Kath-Kuni architecture).',
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop&auto=format',
    sustainabilityScore: 89,
    accessibilitySummary: 'Ground floor dining and courtyard accessible.',
    sustainabilityPractices: ['Kath-Kuni seismic heritage architecture', 'Solar thermal underfloor heating', 'Kullu apple agroforestry', 'Zero plastic refill hub'],
    accessibilityFeatures: [
      { feature: 'Step-free entrance', available: true },
      { feature: 'Accessible parking', available: true },
      { feature: 'Accessible toilet', available: true },
      { feature: 'Elevator', available: false },
      { feature: 'Accessible rooms', available: true },
    ],
    priceRange: '₹3,200–6,000/night',
    rating: 4.8,
    reviews: 134,
  },
]

// ─── Reports ────────────────────────────────────────────────────────────────
export const reports: Report[] = [
  {
    id: 'rpt-1',
    userId: 'user-2',
    destinationId: 'matheran',
    category: 'waste',
    description: 'Large pile of plastic waste near Echo Point. Overflowing bins and litter scattered on the trail.',
    latitude: 18.9847,
    longitude: 73.2653,
    status: 'under_review',
    priority: 'high',
    createdAt: '2025-08-28T14:30:00Z',
  },
  {
    id: 'rpt-2',
    userId: 'user-1',
    destinationId: 'matheran',
    category: 'accessibility',
    description: 'Wheelchair ramp near the main market is blocked by parked motorbikes.',
    latitude: 18.9878,
    longitude: 73.2670,
    status: 'confirmed',
    priority: 'high',
    createdAt: '2025-08-27T10:15:00Z',
  },
  {
    id: 'rpt-3',
    userId: 'user-3',
    destinationId: 'matheran',
    category: 'overcrowding',
    description: 'Extreme overcrowding at Panorama Point. Over 200 people at the viewpoint.',
    latitude: 18.9812,
    longitude: 73.2698,
    status: 'submitted',
    priority: 'medium',
    createdAt: '2025-08-26T16:45:00Z',
  },
  {
    id: 'rpt-4',
    userId: 'user-2',
    destinationId: 'goa',
    category: 'environmental_damage',
    description: 'Illegal construction activity near the beach mangrove area.',
    latitude: 15.2993,
    longitude: 74.1240,
    status: 'in_progress',
    priority: 'critical',
    createdAt: '2025-08-25T09:00:00Z',
  },
  {
    id: 'rpt-5',
    userId: 'user-1',
    destinationId: 'manali',
    category: 'waste',
    description: 'Accumulated garbage near the Hadimba Temple parking area. No bins available.',
    latitude: 32.2432,
    longitude: 77.1892,
    status: 'submitted',
    priority: 'high',
    createdAt: '2025-08-24T13:20:00Z',
  },
  {
    id: 'rpt-6',
    userId: 'user-3',
    destinationId: 'matheran',
    category: 'waste',
    description: 'Plastic bottles and food waste dumped along the forest trail near Pisoli.',
    latitude: 18.9801,
    longitude: 73.2612,
    status: 'submitted',
    priority: 'high',
    createdAt: '2025-08-28T11:00:00Z',
  },
  {
    id: 'rpt-7',
    userId: 'user-2',
    destinationId: 'matheran',
    category: 'waste',
    description: 'Overflowing garbage bin near the toy train station.',
    latitude: 18.9865,
    longitude: 73.2645,
    status: 'under_review',
    priority: 'medium',
    createdAt: '2025-08-27T17:30:00Z',
  },
  {
    id: 'rpt-8',
    userId: 'user-1',
    destinationId: 'matheran',
    category: 'infrastructure',
    description: 'Broken footpath near Louisa Point. Several loose stones creating tripping hazard.',
    latitude: 18.9830,
    longitude: 73.2680,
    status: 'resolved',
    priority: 'medium',
    createdAt: '2025-08-20T08:45:00Z',
  },
]

// ─── AI Insights ────────────────────────────────────────────────────────────
export const aiInsights: AIInsight[] = [
  {
    id: 'insight-1',
    destinationId: 'matheran',
    type: 'hotspot',
    title: 'Waste Hotspot Detected',
    description: 'Waste accumulation is increasing near Echo Point and the forest trail. 37 reports in the last 4 days, concentrated within 500m of Lake Road.',
    reportCount: 37,
    trend: '4-day increasing trend',
    recommendation: 'Increase waste collection frequency during evening hours (5 PM–8 PM) and add temporary bins near Echo Point.',
    severity: 'high',
  },
  {
    id: 'insight-2',
    destinationId: 'matheran',
    type: 'trend',
    title: 'Visitor Pressure Surge',
    description: 'Visitor pressure has increased 28% this weekend compared to last week. Peak overcrowding at Panorama Point.',
    reportCount: 15,
    trend: '28% weekend increase',
    recommendation: 'Promote alternative viewpoints like Forest Trail and Louisa Point to distribute visitor load.',
    severity: 'high',
  },
  {
    id: 'insight-3',
    destinationId: 'matheran',
    type: 'recommendation',
    title: 'Accessibility Improvement Opportunity',
    description: 'Three accessibility complaints were reported near the north entrance and market area in the past week.',
    reportCount: 3,
    trend: 'Steady',
    recommendation: 'Review and clear accessibility ramps near the main market. Consider adding accessible pathways to popular viewpoints.',
    severity: 'medium',
  },
  {
    id: 'insight-4',
    destinationId: 'goa',
    type: 'hotspot',
    title: 'Coastal Erosion Risk',
    description: 'Multiple reports of beach erosion near popular North Goa beaches. Environmental damage reports increasing.',
    reportCount: 12,
    trend: '2-week increasing trend',
    recommendation: 'Restrict construction near mangrove areas and promote South Goa alternatives for peak-season visitors.',
    severity: 'critical',
  },
  {
    id: 'insight-5',
    destinationId: 'manali',
    type: 'trend',
    title: 'Waste Management Strain',
    description: 'Waste reports around Hadimba Temple area have increased 17% this month.',
    reportCount: 22,
    trend: '17% monthly increase',
    recommendation: 'Deploy additional waste collection bins and increase pickup frequency near temple and parking areas.',
    severity: 'medium',
  },
]

// ─── Badges ─────────────────────────────────────────────────────────────────
export const badges: Badge[] = [
  { id: 'badge-1', name: 'Responsible Traveler', description: 'Completed your first challenge', icon: '🌟', ruleKey: 'first_challenge', earned: true, earnedAt: '2025-08-20' },
  { id: 'badge-2', name: 'Waste Warrior', description: 'Completed 3 waste-related challenges', icon: '♻️', ruleKey: 'waste_3', earned: true, earnedAt: '2025-08-22' },
  { id: 'badge-3', name: 'Trail Guardian', description: 'Stayed on designated trails 5 times', icon: '🥾', ruleKey: 'trail_5', earned: true, earnedAt: '2025-08-25' },
  { id: 'badge-4', name: 'Local Supporter', description: 'Supported 3 local businesses', icon: '🏘️', ruleKey: 'local_3', earned: true, earnedAt: '2025-08-26' },
  { id: 'badge-5', name: 'Eco Reporter', description: 'Submitted 3 quality reports', icon: '📋', ruleKey: 'report_3', earned: true, earnedAt: '2025-08-27' },
  { id: 'badge-6', name: 'Green Explorer', description: 'Visited 3 sustainable destinations', icon: '🌍', ruleKey: 'dest_3', earned: true, earnedAt: '2025-08-28' },
  { id: 'badge-7', name: 'Water Saver', description: 'Complete 5 water conservation challenges', icon: '💧', ruleKey: 'water_5', earned: false },
  { id: 'badge-8', name: 'Community Champion', description: 'Help 10 fellow travelers', icon: '🤝', ruleKey: 'help_10', earned: false },
  { id: 'badge-9', name: 'Impact Legend', description: 'Reach 1000 impact points', icon: '🏆', ruleKey: 'points_1000', earned: false },
  { id: 'badge-10', name: 'Streak Master', description: 'Complete challenges 7 days in a row', icon: '🔥', ruleKey: 'streak_7', earned: false },
]

// ─── Social Posts ───────────────────────────────────────────────────────────
export const socialPosts: SocialPost[] = [
  {
    id: 'post-1',
    userId: 'user-3',
    destinationId: 'matheran',
    caption: 'Skipped the crowded viewpoints today and hiked the quiet Charlotte Lake forest canopy trail in Matheran 🌿 Zero vehicle noise, pure nature!',
    imageUrl: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800&h=600&fit=crop&auto=format',
    likes: 142,
    comments: 23,
    createdAt: '2025-08-28T16:30:00Z',
    challengeCompletion: { challengeName: 'Trail Guardian', points: 35 },
    author: { name: 'Sneha Patel', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&auto=format', username: '@snehawanders' },
    destination: 'Matheran, Maharashtra',
  },
  {
    id: 'post-2',
    userId: 'user-2',
    destinationId: 'matheran',
    caption: 'Completed the Waste-Free Trail challenge at Louisa Point! Collected 5 pieces of litter along the Sahyadri ridge. Small actions, big impact. ♻️',
    imageUrl: 'https://www.clubmahindra.com/blog/images/Matheran-resized.jpg',
    likes: 98,
    comments: 15,
    createdAt: '2025-08-27T18:00:00Z',
    challengeCompletion: { challengeName: 'Waste-Free Trail', points: 25 },
    author: { name: 'Arjun Mehta', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&auto=format', username: '@arjun_eco' },
    destination: 'Matheran, Maharashtra',
  },
  {
    id: 'post-3',
    userId: 'user-1',
    destinationId: 'goa',
    caption: 'Explored the organic spice plantations in Ponda and quiet crescent of Palolem Beach in South Goa! Supporting local regenerative farms 🌶️🌴',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop&auto=format',
    likes: 215,
    comments: 34,
    createdAt: '2025-08-26T11:00:00Z',
    author: { name: 'Priya Sharma', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&auto=format', username: '@priyatravels' },
    destination: 'South Goa',
  },
  {
    id: 'post-4',
    userId: 'user-3',
    destinationId: 'manali',
    caption: 'Trek to Jogini Waterfall & Hadimba deodar forest in Manali was breathtaking! Stayed strictly on marked trails. Respect the Himalayas 🏔️',
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop&auto=format',
    likes: 189,
    comments: 28,
    createdAt: '2025-08-25T14:00:00Z',
    challengeCompletion: { challengeName: 'Mountain Trail Respecter', points: 35 },
    author: { name: 'Sneha Patel', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&auto=format', username: '@snehawanders' },
    destination: 'Manali, Himachal Pradesh',
  },
]

// ─── Creators & Campaigns ───────────────────────────────────────────────────
export const creators: Creator[] = [
  {
    id: 'creator-1',
    name: 'Sneha Patel',
    handle: '@snehawanders',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&auto=format',
    followers: 12400,
    campaigns: 3,
    bio: 'Responsible travel creator. Showing India\'s beauty without the footprint.',
  },
  {
    id: 'creator-2',
    name: 'Vikram Singh',
    handle: '@mountainvibes',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&auto=format',
    followers: 8900,
    campaigns: 2,
    bio: 'Himalayan mountain explorer and high-altitude conservation advocate.',
  },
  {
    id: 'creator-3',
    name: 'Ananya Rao',
    handle: '@coastalcalls',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&auto=format',
    followers: 15200,
    campaigns: 4,
    bio: 'Coastal India and Western Ghats through a sustainable lens.',
  },
]

export const campaigns: Campaign[] = [
  {
    id: 'campaign-1',
    creatorId: 'creator-1',
    destinationId: 'matheran',
    title: 'Matheran Zero-Emission Weekend',
    description: 'Explore Matheran\'s red earth trails on foot and complete 2 Leave-No-Trace challenges. Show the world that hill stations can thrive with mindful travel.',
    coverImageUrl: 'https://www.clubmahindra.com/blog/images/Matheran-resized.jpg',
    participants: 234,
    challengeCount: 3,
    status: 'active',
  },
  {
    id: 'campaign-2',
    creatorId: 'creator-3',
    destinationId: 'goa',
    title: 'Go Beyond the Beach: Green Goa',
    description: 'Discover Goa\'s interior — organic spice plantations, Mandovi island cycling, and heritage walks supporting local artisans.',
    coverImageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1000&h=600&fit=crop&auto=format',
    participants: 187,
    challengeCount: 2,
    status: 'active',
  },
]
