import "server-only";

import { DESTINATIONS } from "@/lib/destinations";
import {
  CHILD_NEED_LABELS,
  ELDERLY_PRIORITY_LABELS,
  MOBILITY_NEED_LABELS,
  TRANSPORT_LABELS,
} from "@/lib/trip-options";
import type { AiOption, TripRequestSummary } from "@/lib/trip-schema";
import type { TripProfileSnapshot } from "@/lib/trip-service";

/**
 * Deterministic, application-owned prototype plan.
 *
 * Used only when every configured OpenRouter model is unreachable (the free
 * pool is frequently congested). Everything here is generated by OUR code from
 * our own prototype dataset — it is clearly labelled as prototype/estimated in
 * the UI and is never presented as verified real-world information.
 *
 * It emits the same shape the AI is asked for, so it flows through the exact
 * same validation + normalization pipeline and the same UI.
 */

function anchorFor(destination: string) {
  const needle = destination.trim().toLowerCase();
  return DESTINATIONS.find(
    (item) =>
      item.name.toLowerCase() === needle ||
      item.id === needle ||
      needle.includes(item.name.toLowerCase()),
  );
}

/**
 * Which transport mode each option uses. Option A always aims for the lower
 * estimated emissions; Option B optimises for comfort while staying accessible.
 */
function pickModes(preference: string): { a: string; b: string } {
  switch (preference) {
    case "public_transport":
      return { a: "train", b: "car" };
    case "bus":
      return { a: "bus", b: "car" };
    case "private_vehicle":
      return { a: "mixed", b: "car" };
    case "ev_shared":
      return { a: "ev", b: "ev" };
    case "walking":
      return { a: "walk", b: "mixed" };
    case "lowest_impact":
      return { a: "train", b: "ev" };
    case "surprise":
    default:
      return { a: "train", b: "car" };
  }
}

const MODE_ACTIVITY: Record<string, string> = {
  train: "Train journey",
  bus: "Intercity coach",
  car: "Private car journey",
  ev: "Electric / shared ride",
  walk: "Walk to the stay",
  mixed: "Mixed-mode journey",
};

function accessibilityLine(snapshot: TripProfileSnapshot): string {
  const parts: string[] = [];
  if (snapshot.mobility.length > 0) parts.push("step-free route planned");
  if (snapshot.mobility.includes("elevator")) parts.push("lift available");
  if (snapshot.mobility.includes("seating_areas") || snapshot.mobility.includes("minimal_walking")) {
    parts.push("frequent seating");
  }
  if (snapshot.travelerTypes.includes("wheelchair_user")) {
    parts.push("wheelchair-accessible transport requested");
  }
  if (parts.length === 0) parts.push("accessibility notes added for review");
  return parts.join("; ");
}

function comfortLine(variant: "a" | "b"): string {
  return variant === "a"
    ? "Slower but lower-impact where the route allows."
    : "Fewer transfers and a more relaxed pace.";
}

export function buildPrototypeOptions(
  request: TripRequestSummary,
  snapshot: TripProfileSnapshot,
): AiOption[] {
  const anchor = anchorFor(request.to);
  const baseAccessibility = anchor?.baseAccessibility ?? 78;
  const baseSustainability = anchor?.sustainability ?? 78;

  const mobilityScore = snapshot.mobility.length > 0 ? -4 : 0;
  const needNote = accessibilityLine(snapshot);

  const modes = pickModes(request.transportPreference);
  const preferenceNote =
    request.additionalPreferences.trim().length > 0
      ? ` We've noted: ${request.additionalPreferences.trim().slice(0, 160)}.`
      : "";

  const tripNeeds = request.tripNeeds
    .map(
      (slug) =>
        ELDERLY_PRIORITY_LABELS[slug] ??
        MOBILITY_NEED_LABELS[slug] ??
        CHILD_NEED_LABELS[slug] ??
        slug,
    )
    .filter((value) => value.length > 0);
  const needSentence =
    tripNeeds.length > 0
      ? ` Kept front of mind: ${tripNeeds.slice(0, 4).join(", ")}.`
      : "";

  const stayPerNight = (
    share: number,
  ): number => Math.max(600, Math.round((request.budget * share) / request.nights / 50) * 50);

  const options: AiOption[] = [
    {
      optionId: "option_a",
      title: "Low-Impact & Accessible",
      tagline: "Lower estimated emissions, practical travel time",
      description:
        `A calm ${request.days}-day plan from ${request.from} to ${request.to} built around lower-impact travel and step-free stops.${needSentence}${preferenceNote}`,
      focus: ["Lower estimated CO₂", "Strong accessibility", "Lower-impact stay"],
      highlights: [
        "Lower-emission travel where the route allows",
        "Step-free viewpoints and gentle pacing",
        "Locally-run, lower-impact accommodation",
      ],
      safetyNotes: needNote,
      transport: {
        mode: modes.a,
        label: TRANSPORT_LABELS[request.transportPreference] ?? modes.a,
        notes: comfortLine("a"),
        cost: 0,
      },
      stay: {
        name: `${request.to} Green Stay`,
        type: "Prototype lower-impact stay",
        costPerNight: stayPerNight(0.28),
        accessibilityScore: Math.max(55, Math.min(97, baseAccessibility + mobilityScore)),
        sustainabilityScore: Math.min(97, baseSustainability + 6),
        features: ["Prototype: step-free access", "Prototype: solar water", "Prototype: local sourcing"],
        notes: "Prototype planning attributes — confirm with the property before booking.",
      },
      experiences: [
        {
          title: "Accessible viewpoint",
          description: "A shorter route to a level lookout with seating.",
          accessibilityScore: Math.max(55, Math.min(97, baseAccessibility + 2)),
          sustainabilityLabel: "Lower impact",
          cost: Math.round(request.budget * 0.01),
        },
        {
          title: "Locally-sourced meal",
          description: "A small, quieter restaurant with a written menu.",
          accessibilityScore: Math.max(55, Math.min(97, baseAccessibility)),
          sustainabilityLabel: "Lower impact",
          cost: Math.round(request.budget * 0.015),
        },
        {
          title: "Market & garden visit",
          description: "A flat, shaded walk close to your stay.",
          accessibilityScore: Math.max(55, Math.min(97, baseAccessibility)),
          sustainabilityLabel: "Lower impact",
          cost: Math.round(request.budget * 0.01),
        },
      ],
      accessibilityScore: Math.max(55, Math.min(97, baseAccessibility + mobilityScore)),
      sustainabilityScore: Math.min(97, baseSustainability + 6),
      days: buildDays(request, modes.a, needNote, "a"),
    },
    {
      optionId: "option_b",
      title: "Comfort & Experience",
      tagline: "More comfort and more to do, reasonable impact",
      description:
        `A more comfortable ${request.days}-day plan from ${request.from} to ${request.to} with fewer transfers and more experiences.${needSentence}${preferenceNote}`,
      focus: ["More comfort", "Strong accessibility", "More experiences"],
      highlights: [
        "Fewer transfers and door-to-door comfort",
        "Extra experiences and dining",
        "Comfortable, accessible accommodation",
      ],
      safetyNotes: needNote,
      transport: {
        mode: modes.b,
        label: `${TRANSPORT_LABELS[request.transportPreference] ?? modes.b} (comfort)`,
        notes: comfortLine("b"),
        cost: 0,
      },
      stay: {
        name: `${request.to} Comfort Retreat`,
        type: "Prototype comfortable stay",
        costPerNight: stayPerNight(0.38),
        accessibilityScore: Math.max(58, Math.min(98, baseAccessibility + 4 + mobilityScore)),
        sustainabilityScore: Math.min(95, baseSustainability - 6),
        features: ["Prototype: step-free access", "Prototype: lift", "Prototype: quiet rooms"],
        notes: "Prototype planning attributes — confirm with the property before booking.",
      },
      experiences: [
        {
          title: "Guided heritage walk (short)",
          description: "An easy, mostly level route with plenty of stops.",
          accessibilityScore: Math.max(58, Math.min(98, baseAccessibility + 4)),
          sustainabilityLabel: "Moderate impact",
          cost: Math.round(request.budget * 0.02),
        },
        {
          title: "Scenic cable-car or lift ride",
          description: "Big views with very little walking.",
          accessibilityScore: Math.max(58, Math.min(98, baseAccessibility + 6)),
          sustainabilityLabel: "Moderate impact",
          cost: Math.round(request.budget * 0.03),
        },
        {
          title: "Signature local dinner",
          description: "A comfortable restaurant with staff assistance.",
          accessibilityScore: Math.max(58, Math.min(98, baseAccessibility + 2)),
          sustainabilityLabel: "Moderate impact",
          cost: Math.round(request.budget * 0.035),
        },
        {
          title: "Relaxed spa or café afternoon",
          description: "Unhurried time with accessible facilities.",
          accessibilityScore: Math.max(58, Math.min(98, baseAccessibility + 4)),
          sustainabilityLabel: "Moderate impact",
          cost: Math.round(request.budget * 0.02),
        },
      ],
      accessibilityScore: Math.max(58, Math.min(98, baseAccessibility + 4 + mobilityScore)),
      sustainabilityScore: Math.min(95, baseSustainability - 6),
      days: buildDays(request, modes.b, needNote, "b"),
    },
  ];

  return options;
}

function buildDays(
  request: TripRequestSummary,
  mode: string,
  needNote: string,
  variant: "a" | "b",
): AiOption["days"] {
  const total = request.days;
  const days: AiOption["days"] = [];

  for (let index = 0; index < total; index += 1) {
    const isFirst = index === 0;
    const isLast = index === total - 1 && total > 1;

    if (isFirst) {
      days.push({
        day: 1,
        title: "Travel and settle in",
        summary: `Head from ${request.from} to ${request.to} and take the first afternoon at an easy pace.`,
        activities: [
          {
            time: "08:00",
            title: `${MODE_ACTIVITY[mode]} to ${request.to}`,
            location: `${request.from} → ${request.to}`,
            transport: mode,
            cost: 0,
            accessibility: needNote,
            sustainability: "Lower-impact travel option where available.",
            co2Kg: 0,
          },
          {
            time: "13:00",
            title: "Check-in and rest",
            location: request.to,
            transport: "",
            cost: 0,
            accessibility: needNote,
            sustainability: "Locally-run stay.",
            co2Kg: 0,
          },
          {
            time: "15:30",
            title: variant === "a" ? "Easy viewpoint visit" : "Short orientation stroll",
            location: request.to,
            transport: mode,
            cost: Math.round(request.budget * 0.01),
            accessibility: "Flat, step-free route with seating.",
            sustainability: "Small-group, low-waste activity.",
            co2Kg: 0,
          },
          {
            time: "19:00",
            title: "Dinner nearby",
            location: request.to,
            transport: "Walk",
            cost: Math.round(request.budget * 0.015),
            accessibility: "Written menu and step-free entry.",
            sustainability: "Locally sourced menu.",
            co2Kg: 0,
          },
        ],
      });
      continue;
    }

    if (isLast) {
      days.push({
        day: index + 1,
        title: "Last morning and journey home",
        summary: "A gentle final morning, then the return journey with plenty of buffer time.",
        activities: [
          {
            time: "09:00",
            title: "Breakfast and pack",
            location: request.to,
            transport: "",
            cost: Math.round(request.budget * 0.01),
            accessibility: needNote,
            sustainability: "Waste-reducing stay.",
            co2Kg: 0,
          },
          {
            time: "11:00",
            title: "Check out",
            location: request.to,
            transport: "",
            cost: 0,
            accessibility: "Assistance available on request.",
            sustainability: "",
            co2Kg: 0,
          },
          {
            time: "12:30",
            title: `${MODE_ACTIVITY[mode]} back to ${request.from}`,
            location: `${request.to} → ${request.from}`,
            transport: mode,
            cost: 0,
            accessibility: needNote,
            sustainability: "Lower-impact travel option where available.",
            co2Kg: 0,
          },
        ],
      });
      continue;
    }

    days.push({
      day: index + 1,
      title: variant === "a" ? "Nature and gentle exploring" : "Experiences and comfort",
      summary:
        variant === "a"
          ? "A low-impact day with shaded stops and time to rest."
          : "A fuller day of experiences with comfortable pauses built in.",
      activities: [
        {
          time: "09:00",
          title: variant === "a" ? "Guided nature walk (short)" : "Guided heritage walk",
          location: request.to,
          transport: "",
          cost: Math.round(request.budget * 0.02),
          accessibility: "Mostly level, with rest points.",
          sustainability: "Small-group activity.",
          co2Kg: 0,
        },
        {
          time: "11:30",
          title: "Lunch and a long break",
          location: request.to,
          transport: "Walk",
          cost: Math.round(request.budget * 0.02),
          accessibility: "Step-free seating and accessible washrooms.",
          sustainability: "Local produce.",
          co2Kg: 0,
        },
        {
          time: "14:00",
          title: variant === "a" ? "Accessible viewpoint" : "Scenic lift / cable car",
          location: request.to,
          transport: variant === "a" ? "Walk" : mode,
          cost: Math.round(request.budget * 0.03),
          accessibility: needNote,
          sustainability: "Lower-emission option where possible.",
          co2Kg: 0,
        },
        {
          time: "16:30",
          title: "Rest at the stay",
          location: request.to,
          transport: "",
          cost: 0,
          accessibility: "Quiet rooms and lift access.",
          sustainability: "",
          co2Kg: 0,
        },
        {
          time: "19:30",
          title: "Dinner",
          location: request.to,
          transport: "Walk",
          cost: Math.round(request.budget * 0.025),
          accessibility: "Written menu and step-free entry.",
          sustainability: "Locally sourced menu.",
          co2Kg: 0,
        },
      ],
    });
  }

  return days;
}
