import "server-only";

import { DESTINATIONS } from "@/lib/destinations";
import {
  CHILD_NEED_LABELS,
  ELDERLY_PRIORITY_LABELS,
  MOBILITY_NEED_LABELS,
} from "@/lib/trip-options";
import type { AiOption, TripRequestSummary } from "@/lib/trip-schema";
import type { TripProfileSnapshot } from "@/lib/trip-service";

/**
 * Deterministic, application-owned prototype plan.
 *
 * Used only when every configured OpenRouter model is unreachable (the free
 * pool is frequently congested). Everything here is generated by OUR code from
 * our own prototype dataset — it is clearly labelled as prototype/estimated in
 * the UI and is never presented as verified real-world information.
 *
 * It emits the same shape the AI is asked for, so it flows through the exact
 * same validation + normalization pipeline and the same UI. It always produces
 * FOUR options, and every one of them stays in the Low or Moderate
 * environmental-impact band — that is the constant axis the traveller chooses
 * on.
 */

function anchorFor(destination: string) {
  const needle = destination.trim().toLowerCase();
  return DESTINATIONS.find(
    (item) =>
      item.name.toLowerCase() === needle ||
      item.id === needle ||
      needle.includes(item.name.toLowerCase()),
  );
}

/**
 * Transport per option. Every pairing deliberately avoids the higher-emission
 * modes so the four plans stay comparable on environmental impact.
 */
function pickModes(preference: string): {
  a: string;
  b: string;
  c: string;
  d: string;
} {
  switch (preference) {
    case "public_transport":
      return { a: "train", b: "ev", c: "bus", d: "mixed" };
    case "bus":
      return { a: "bus", b: "ev", c: "train", d: "mixed" };
    case "private_vehicle":
      return { a: "ev", b: "mixed", c: "bus", d: "train" };
    case "ev_shared":
      return { a: "ev", b: "mixed", c: "bus", d: "train" };
    case "walking":
      return { a: "walk", b: "mixed", c: "bus", d: "train" };
    case "lowest_impact":
      return { a: "train", b: "ev", c: "bus", d: "mixed" };
    case "surprise":
    default:
      return { a: "train", b: "ev", c: "bus", d: "mixed" };
  }
}

const MODE_ACTIVITY: Record<string, string> = {
  train: "Train journey",
  bus: "Intercity coach",
  car: "Private car journey",
  ev: "Electric / shared ride",
  walk: "Walk to the stay",
  mixed: "Mixed-mode journey",
};

function accessibilityLine(snapshot: TripProfileSnapshot): string {
  const parts: string[] = [];
  if (snapshot.mobility.length > 0) parts.push("step-free route planned");
  if (snapshot.mobility.includes("elevator")) parts.push("lift available");
  if (
    snapshot.mobility.includes("seating_areas") ||
    snapshot.mobility.includes("minimal_walking")
  ) {
    parts.push("frequent seating");
  }
  if (snapshot.travelerTypes.includes("wheelchair_user")) {
    parts.push("wheelchair-accessible transport requested");
  }
  if (parts.length === 0) parts.push("accessibility notes added for review");
  return parts.join("; ");
}

type Archetype = {
  key: string;
  optionId: string;
  title: string;
  tagline: string;
  focus: string[];
  highlights: string[];
  /** Share of the budget spent on the stay each night. */
  stayShare: number;
  /** Accessibility delta applied to the destination's base score. */
  accDelta: number;
  /** Sustainability delta applied to the destination's base score. */
  susDelta: number;
  stayName: (to: string) => string;
  stayType: string;
  stayFeatures: string[];
  experiences: { title: string; description: string; impact: string; share: number }[];
  transportNote: string;
};

const ARCHETYPES: Archetype[] = [
  {
    key: "greenest",
    optionId: "option_a",
    title: "Greenest & Accessible",
    tagline: "The lowest estimated CO₂ we could find for your route",
    focus: ["Lowest estimated CO₂", "Strong accessibility", "Lower-impact stay"],
    highlights: [
      "Lowest-emission travel the route allows",
      "Step-free viewpoints and a gentle pace",
      "Locally-run, lower-impact accommodation",
    ],
    stayShare: 0.26,
    accDelta: 0,
    susDelta: 8,
    stayName: (to) => `${to} Green Stay`,
    stayType: "Prototype lower-impact stay",
    stayFeatures: [
      "Prototype: step-free access",
      "Prototype: solar water",
      "Prototype: local sourcing",
    ],
    experiences: [
      {
        title: "Accessible viewpoint",
        description: "A shorter route to a level lookout with seating.",
        impact: "Lower impact",
        share: 0.01,
      },
      {
        title: "Locally-sourced meal",
        description: "A small, quieter restaurant with a written menu.",
        impact: "Lower impact",
        share: 0.015,
      },
      {
        title: "Market and garden visit",
        description: "A flat, shaded walk close to your stay.",
        impact: "Lower impact",
        share: 0.01,
      },
    ],
    transportNote: "Slower but lower-impact where the route allows.",
  },
  {
    key: "comfort",
    optionId: "option_b",
    title: "Comfort First",
    tagline: "Fewer transfers and the most comfortable stay",
    focus: ["Most comfortable", "Highest accessibility", "Fewer transfers"],
    highlights: [
      "Door-to-door comfort with fewer changes",
      "Quiet, accessible rooms and lifts",
      "Unhurried days with plenty of pauses",
    ],
    stayShare: 0.44,
    accDelta: 5,
    susDelta: 2,
    stayName: (to) => `${to} Comfort Retreat`,
    stayType: "Prototype comfortable stay",
    stayFeatures: [
      "Prototype: step-free access",
      "Prototype: lift",
      "Prototype: quiet rooms",
    ],
    experiences: [
      {
        title: "Guided heritage walk (short)",
        description: "An easy, mostly level route with plenty of stops.",
        impact: "Moderate impact",
        share: 0.02,
      },
      {
        title: "Scenic lift or cable car",
        description: "Big views with very little walking.",
        impact: "Moderate impact",
        share: 0.025,
      },
      {
        title: "Signature local dinner",
        description: "A comfortable restaurant with staff assistance.",
        impact: "Moderate impact",
        share: 0.03,
      },
      {
        title: "Relaxed spa or café afternoon",
        description: "Unhurried time with accessible facilities.",
        impact: "Moderate impact",
        share: 0.015,
      },
    ],
    transportNote: "Fewer transfers and a much more relaxed pace.",
  },
  {
    key: "value",
    optionId: "option_c",
    title: "Best Value",
    tagline: "The lowest estimated cost, without losing accessibility",
    focus: ["Lowest estimated cost", "Strong accessibility", "Good value stay"],
    highlights: [
      "Public transport keeps the fare down",
      "Solid accessibility at every stop",
      "Good-value, locally-run accommodation",
    ],
    stayShare: 0.18,
    accDelta: 2,
    susDelta: 0,
    stayName: (to) => `${to} Value Guesthouse`,
    stayType: "Prototype good-value stay",
    stayFeatures: [
      "Prototype: step-free entry",
      "Prototype: family-run",
      "Prototype: near transport",
    ],
    experiences: [
      {
        title: "Free walking route",
        description: "A flat, self-guided loop from your stay.",
        impact: "Lower impact",
        share: 0.005,
      },
      {
        title: "Local market browse",
        description: "Shaded lanes with plenty of places to sit.",
        impact: "Lower impact",
        share: 0.008,
      },
      {
        title: "Simple local thali",
        description: "An easy, well-priced meal with a written menu.",
        impact: "Lower impact",
        share: 0.01,
      },
    ],
    transportNote: "Public transport keeps the cost down; slightly more changes.",
  },
  {
    key: "experiences",
    optionId: "option_d",
    title: "Experience-Rich",
    tagline: "More to see and do, still lower-impact",
    focus: ["Most experiences", "Strong accessibility", "Lively pace"],
    highlights: [
      "The fullest set of experiences",
      "Still accessible and step-free",
      "Locally-run activities, lower waste",
    ],
    stayShare: 0.32,
    accDelta: 3,
    susDelta: -2,
    stayName: (to) => `${to} Trailside Lodge`,
    stayType: "Prototype experience-led stay",
    stayFeatures: [
      "Prototype: step-free access",
      "Prototype: activity desk",
      "Prototype: quiet rooms",
    ],
    experiences: [
      {
        title: "Guided nature trail (short)",
        description: "Mostly level, with rest points along the way.",
        impact: "Lower impact",
        share: 0.02,
      },
      {
        title: "Local craft workshop",
        description: "A hands-on session with step-free access.",
        impact: "Lower impact",
        share: 0.03,
      },
      {
        title: "Sunset viewpoint ride",
        description: "A short, accessible transfer to a level lookout.",
        impact: "Moderate impact",
        share: 0.025,
      },
      {
        title: "Tasting menu evening",
        description: "A local menu with dietary options on request.",
        impact: "Moderate impact",
        share: 0.035,
      },
      {
        title: "Heritage quarter stroll",
        description: "Plenty of seating and accessible washrooms.",
        impact: "Lower impact",
        share: 0.02,
      },
    ],
    transportNote: "A mix of modes to fit in more, kept within lower impact.",
  },
];

export function buildPrototypeOptions(
  request: TripRequestSummary,
  snapshot: TripProfileSnapshot,
): AiOption[] {
  const anchor = anchorFor(request.to);
  const baseAccessibility = anchor?.baseAccessibility ?? 78;
  const baseSustainability = anchor?.sustainability ?? 78;

  const mobilityScore = snapshot.mobility.length > 0 ? -4 : 0;
  const needNote = accessibilityLine(snapshot);

  const modes = pickModes(request.transportPreference);
  const preferenceNote =
    request.additionalPreferences.trim().length > 0
      ? ` We've noted: ${request.additionalPreferences.trim().slice(0, 160)}.`
      : "";

  const tripNeeds = request.tripNeeds
    .map(
      (slug) =>
        ELDERLY_PRIORITY_LABELS[slug] ??
        MOBILITY_NEED_LABELS[slug] ??
        CHILD_NEED_LABELS[slug] ??
        slug,
    )
    .filter((value) => value.length > 0);
  const needSentence =
    tripNeeds.length > 0
      ? ` Kept front of mind: ${tripNeeds.slice(0, 4).join(", ")}.`
      : "";

  const stayPerNight = (share: number): number =>
    Math.max(600, Math.round((request.budget * share) / request.nights / 50) * 50);

  const clamp = (value: number, min: number, max: number) =>
    Math.max(min, Math.min(max, Math.round(value)));

  return ARCHETYPES.map((archetype) => {
    const mode = modes[archetype.key[0] as "a" | "b" | "c" | "d"];
    const accessScore = clamp(
      baseAccessibility + archetype.accDelta + mobilityScore,
      55,
      98,
    );
    const sustainScore = clamp(
      baseSustainability + archetype.susDelta,
      55,
      98,
    );

    return {
      optionId: archetype.optionId,
      title: archetype.title,
      tagline: archetype.tagline,
      description:
        `A ${request.days}-day ${archetype.title.toLowerCase()} plan from ${request.from} to ${request.to}, built around lower-impact travel and step-free stops.${needSentence}${preferenceNote}`,
      focus: archetype.focus,
      highlights: archetype.highlights,
      safetyNotes: needNote,
      transport: {
        mode,
        // Labelled by the mode we actually chose, so four plans that use
        // different travel never all read as the traveller's first preference.
        label: MODE_ACTIVITY[mode] ?? mode,
        notes: archetype.transportNote,
        cost: 0,
      },
      stay: {
        name: archetype.stayName(request.to),
        type: archetype.stayType,
        costPerNight: stayPerNight(archetype.stayShare),
        accessibilityScore: accessScore,
        sustainabilityScore: sustainScore,
        features: archetype.stayFeatures,
        notes:
          "Prototype planning attributes — confirm with the property before booking.",
      },
      experiences: archetype.experiences.map((experience) => ({
        title: experience.title,
        description: experience.description,
        accessibilityScore: clamp(accessScore + 2, 55, 98),
        sustainabilityLabel: experience.impact,
        cost: Math.round(request.budget * experience.share),
      })),
      accessibilityScore: accessScore,
      sustainabilityScore: sustainScore,
      days: buildDays(request, mode, needNote, archetype.key),
    } satisfies AiOption;
  });
}

type DayKey = string;

function buildDays(
  request: TripRequestSummary,
  mode: string,
  needNote: string,
  variant: DayKey,
): AiOption["days"] {
  const total = request.days;
  const lively = variant === "experiences";
  const gentle = variant === "greenest" || variant === "value";
  const days: AiOption["days"] = [];

  const midDayTitle = gentle
    ? "Nature and gentle exploring"
    : lively
      ? "Experiences and local life"
      : "Comfort and easy exploring";
  const midDaySummary = gentle
    ? "A low-impact day with shaded stops and time to rest."
    : lively
      ? "A fuller day of experiences with comfortable pauses built in."
      : "An unhurried day with fewer transfers and plenty of rest.";

  for (let index = 0; index < total; index += 1) {
    const isFirst = index === 0;
    const isLast = index === total - 1 && total > 1;

    if (isFirst) {
      days.push({
        day: 1,
        title: "Travel and settle in",
        summary: `Head from ${request.from} to ${request.to} and take the first afternoon at an easy pace.`,
        activities: [
          {
            time: "08:00",
            title: `${MODE_ACTIVITY[mode] ?? "Journey"} to ${request.to}`,
            location: `${request.from} → ${request.to}`,
            transport: mode,
            cost: 0,
            accessibility: needNote,
            sustainability: "Lower-impact travel option where available.",
            co2Kg: 0,
          },
          {
            time: "13:00",
            title: "Check-in and rest",
            location: request.to,
            transport: "",
            cost: 0,
            accessibility: needNote,
            sustainability: "Locally-run stay.",
            co2Kg: 0,
          },
          {
            time: "15:30",
            title: gentle ? "Easy viewpoint visit" : "Short orientation stroll",
            location: request.to,
            transport: mode,
            cost: Math.round(request.budget * 0.01),
            accessibility: "Flat, step-free route with seating.",
            sustainability: "Small-group, low-waste activity.",
            co2Kg: 0,
          },
          {
            time: "19:00",
            title: "Dinner nearby",
            location: request.to,
            transport: "Walk",
            cost: Math.round(request.budget * 0.015),
            accessibility: "Written menu and step-free entry.",
            sustainability: "Locally sourced menu.",
            co2Kg: 0,
          },
        ],
      });
      continue;
    }

    if (isLast) {
      days.push({
        day: index + 1,
        title: "Last morning and journey home",
        summary:
          "A gentle final morning, then the return journey with plenty of buffer time.",
        activities: [
          {
            time: "09:00",
            title: "Breakfast and pack",
            location: request.to,
            transport: "",
            cost: Math.round(request.budget * 0.01),
            accessibility: needNote,
            sustainability: "Waste-reducing stay.",
            co2Kg: 0,
          },
          {
            time: "11:00",
            title: "Check out",
            location: request.to,
            transport: "",
            cost: 0,
            accessibility: "Assistance available on request.",
            sustainability: "",
            co2Kg: 0,
          },
          {
            time: "12:30",
            title: `${MODE_ACTIVITY[mode] ?? "Journey"} back to ${request.from}`,
            location: `${request.to} → ${request.from}`,
            transport: mode,
            cost: 0,
            accessibility: needNote,
            sustainability: "Lower-impact travel option where available.",
            co2Kg: 0,
          },
        ],
      });
      continue;
    }

    days.push({
      day: index + 1,
      title: midDayTitle,
      summary: midDaySummary,
      activities: [
        {
          time: "09:00",
          title: lively ? "Guided local trail" : "Guided nature walk (short)",
          location: request.to,
          transport: "",
          cost: Math.round(request.budget * (lively ? 0.025 : 0.02)),
          accessibility: "Mostly level, with rest points.",
          sustainability: "Small-group activity.",
          co2Kg: 0,
        },
        {
          time: "11:30",
          title: "Lunch and a long break",
          location: request.to,
          transport: "Walk",
          cost: Math.round(request.budget * 0.02),
          accessibility: "Step-free seating and accessible washrooms.",
          sustainability: "Local produce.",
          co2Kg: 0,
        },
        {
          time: "14:00",
          title: gentle ? "Accessible viewpoint" : "Scenic lift or cable car",
          location: request.to,
          transport: gentle ? "Walk" : mode,
          cost: Math.round(request.budget * 0.03),
          accessibility: needNote,
          sustainability: "Lower-emission option where possible.",
          co2Kg: 0,
        },
        {
          time: "16:30",
          title: "Rest at the stay",
          location: request.to,
          transport: "",
          cost: 0,
          accessibility: "Quiet rooms and lift access.",
          sustainability: "",
          co2Kg: 0,
        },
        {
          time: "19:30",
          title: "Dinner",
          location: request.to,
          transport: "Walk",
          cost: Math.round(request.budget * 0.025),
          accessibility: "Written menu and step-free entry.",
          sustainability: "Locally sourced menu.",
          co2Kg: 0,
        },
      ],
    });
  }

  return days;
}
